name: sync leetcode
on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 6"
jobs:
  build:
    runs-on: ubuntu - latest
    steps:
    - name: sync
      uses: josh cai/leetcode - sync@v1.7
      with:
        github - token: ${{ github.token }}
        leetcode - csrf - token: ${{ secrets.leetcode_csrf_token }}
        leetcode - session: ${{ secrets.leetcode_session }}
        destination - folder: my - folder
        verbose: true
        commit - header: "(leetcode sync)"
